source:      .
destination: ./_site
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git']

safe:        true
host:        0.0.0.0
port:        4000
baseurl:     /tupi-docs
url:         http://localhost:4000
